import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} style={{ backgroundImage: "radial-gradient(circle, var(--background-dots) 1px, transparent 1px)", backgroundSize: "15px 15px" }}
      >
        <div className="flex flex-col justify-center items-center px-2 max-sm:px-1">
          <Header className="max-w-6xl w-full mt-3 mb-4 px-2 max-sm:px-0" />
          <main className="block max-w-5xl items-center w-full h-full">
            {children}
          </main>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
