import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} style={{ backgroundImage: "radial-gradient(circle, var(--secondary) 1px, transparent 1px)", backgroundSize: "15px 15px" }}
      >
        <div className="flex flex-col justify-center items-center">
          <Header className="max-w-6xl mt-3 w-full pb-3" />
          <main className="block max-w-5xl items-center gap-3 w-full">
            {children}
          </main>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
